general {
  colors = true
  interval = 5
}

order += "disk /"
order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "load"
order += "memory"
order += "tztime local"

disk "/" {
  format = "disk %avail"
}

wireless "_first_" {
  format_up = "W: (%quality at %essid) %ip"
  format_down = "W: down"
}

ethernet "_first_" {
  format_up = "E: %ip (%speed)"
  format_down = "E: down"
}

battery all {
  format = "%status %percentage %remaining"
}

load {
  format = "%1min"
}

memory {
  format = "%used"
}

tztime local {
  format = "%Y-%m-%d %H:%M:%S"
}
